server:
  port: ${PORT:8083}

spring:
  application:
    name: sanidad-service

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/db_sanidad?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:tioroger777}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: ${SHOW_SQL:true}

logging:
  level:
    org.springframework: ${SPRING_LOG_LEVEL:INFO}
    com.tuempresa: ${APP_LOG_LEVEL:DEBUG}